# Generated by Django 2.2.3 on 2019-07-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
