# Generated by Django 2.2.3 on 2019-07-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190731_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag_set',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.ManyToManyField(to='article.Article'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
