# Generated by Django 2.2.3 on 2019-08-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20190802_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='delete',
            field=models.BooleanField(default=0),
        ),
        migrations.DeleteModel(
            name='Delete',
        ),
    ]
