# Generated by Django 2.2.3 on 2019-08-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190803_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='delete',
            field=models.IntegerField(default=0),
        ),
    ]
