# Generated by Django 2.2.3 on 2019-08-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20190803_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='delete',
            field=models.IntegerField(),
        ),
    ]
