# Generated by Django 2.2.3 on 2019-08-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20190803_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='delo',
            field=models.IntegerField(default=1),
        ),
    ]
